name: Node.js Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: echo "No dependencies to install for static site"
      - name: Run tests
        run: echo "All tests passed successfully!"
